/home/riseadmin/.local/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters
/home/riseadmin/.local/lib/python2.7/site-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/home/riseadmin/.local/lib/python2.7/site-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p
/home/riseadmin/anaconda/envs/latest/lib/python2.7/site-packages/sklearn/utils/__init__.py:12: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .murmurhash import murmurhash3_32
/home/riseadmin/anaconda/envs/latest/lib/python2.7/site-packages/sklearn/utils/extmath.py:23: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._logistic_sigmoid import _log_logistic_sigmoid
/home/riseadmin/anaconda/envs/latest/lib/python2.7/site-packages/sklearn/utils/extmath.py:25: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .sparsefuncs_fast import csr_row_norms
/home/riseadmin/anaconda/envs/latest/lib/python2.7/site-packages/sklearn/metrics/cluster/supervised.py:25: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .expected_mutual_info_fast import expected_mutual_information
/home/riseadmin/anaconda/envs/latest/lib/python2.7/site-packages/sklearn/metrics/pairwise.py:31: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .pairwise_fast import _chi2_kernel_fast, _sparse_manhattan
INFO:tensorflow:Starting seq2seq_attention in train mode...
max_size of vocab was specified as 25000; we now have 25000 words. Stopping reading.
Finished constructing vocabulary of 25000 total words. Last word added: uncovering
creating model...
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Building graph...
Writing word embedding metadata file to /media/riseadmin/data2/gttp_64_holle_logs/holle_type_64_updated_gcn_before_lstm_gcn_size_128_use_label_and_gating_entity_hops_1_run_2/train/vocab_metadata.tsv...
Traceback (most recent call last):
  File "run_summarization.py", line 600, in <module>
    tf.app.run()
  File "/home/riseadmin/anaconda/envs/latest/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_summarization.py", line 568, in main
    setup_training(model, batcher)
  File "run_summarization.py", line 236, in setup_training
    model.build_graph() # build the graph
  File "/home/riseadmin/gcn_pointer_generator/model.py", line 1199, in build_graph
    self._add_seq2seq()
  File "/home/riseadmin/gcn_pointer_generator/model.py", line 879, in _add_seq2seq
    use_fusion=hps.word_gcn_fusion.value)
  File "/home/riseadmin/gcn_pointer_generator/model.py", line 398, in _add_gcn_layer
    t_indices = self._word_adj_in_coref[b].indices
TypeError: 'SparseTensor' object does not support indexing
